//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tPing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tPing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad option {0}..
        /// </summary>
        internal static string BadOption {
            get {
                return ResourceManager.GetString("BadOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad parameter {0}..
        /// </summary>
        internal static string BadParameter {
            get {
                return ResourceManager.GetString("BadParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad value for option {0}, valid range is from {1} to {2}..
        /// </summary>
        internal static string BadValueForOption {
            get {
                return ResourceManager.GetString("BadValueForOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find host address..
        /// </summary>
        internal static string CannotFindHost {
            get {
                return ResourceManager.GetString("CannotFindHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}: time={1}ms.
        /// </summary>
        internal static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0} [{1}] on {2} port {3}.
        /// </summary>
        internal static string ConnectingTo {
            get {
                return ResourceManager.GetString("ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed: {0}.
        /// </summary>
        internal static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection statistics:.
        /// </summary>
        internal static string ConnectionStatistics {
            get {
                return ResourceManager.GetString("ConnectionStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Attempted = {0}, Connected = {1}, Failed = {2} ({3:0.00%}).
        /// </summary>
        internal static string ConnectionStatisticsDetail {
            get {
                return ResourceManager.GetString("ConnectionStatisticsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection time:.
        /// </summary>
        internal static string ConnectionTime {
            get {
                return ResourceManager.GetString("ConnectionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 	Minimum = {0:0.00}ms, Maximum = {1:0.00}ms, Average = {2:0.00}ms.
        /// </summary>
        internal static string ConnectionTimeDetail {
            get {
                return ResourceManager.GetString("ConnectionTimeDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tPing v{0}.
        /// </summary>
        internal static string HeaderString {
            get {
                return ResourceManager.GetString("HeaderString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: tping target_name -p port [-t] [-a] [-n count] [-l size] [-f] [-i TTL] [-v TOS]
        ///             [-r count] [-s count] [[-j host-list] | [-k host-list]]
        ///             [-w timeout] [-R] [-S srcaddr] [-c compartment] [-p]
        ///             [-4] [-6] 
        ///
        ///Options:
        ///    -t             Attempt to connect to the specified host until stopped.
        ///                   To stop - press Control-C or Control-Break.
        ///    -a             Resolve address to hostname.
        ///    -n count       Number of attempts to connect.
        ///    -w tim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing option. Try -h for help..
        /// </summary>
        internal static string MissingOption {
            get {
                return ResourceManager.GetString("MissingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be supplied for option {0}..
        /// </summary>
        internal static string MissingValueForOption {
            get {
                return ResourceManager.GetString("MissingValueForOption", resourceCulture);
            }
        }
    }
}
